AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/MethodParameterName:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table

Metrics/MethodLength:
  Max: 20
